export const environment = {
  production: false,
  genres: [
    'Pop',
    'Rock',
    'Jazz',
    'Blues',
    'Country',
    'Folk',
    'Reggae',
    'Hip Hop',
    'R&B',
    'Electronic',
    'Classical',
    'Metal',
    'Punk',
    'Soul',
    'Disco',
    'Funk',
    'Gospel',
    'Techno',
    'House',
    'Trance',
    'Drum and Bass',
    'Dubstep',
    'Ambient',
    'Latin',
    'Reggaeton',
    'Ska',
    'Swing',
    'Bluegrass',
    'Opera',
  ],
  // Configuraciones de ngx-translate
  i18nPrefix: '',
};
